### ISSUE TITLE
Wikibooks page in Japanese

### ISSUE THREAD

**Issue by ty1027** [chapel-lang/ChapelExamplesAndTeachingMaterials#4]
First of all, thank you very much for creating the Examples & Teaching Materials pages!
I believe this kind of page will be useful to quickly reach the most up-to-date materials
to learn Chapel.

(The following is not an urgent issue, but I feel I should report this anyway.)

And looking at the list, I've noticed that it includes the following Wikibooks page
in Japanese, while citing my old post in the Chapel Discourse
(FYI, my account name in the Discourse is "tbzy", with my name "Takeshi Yamamoto").

https://chapel.discourse.group/t/chapel-wikibooks-page/34264
Takashi Yamamoto  Kyoto University https://www.st.keio.ac.jp/en/tprofile/chem/yamamoto.html

While the above item assumes that the Wikipages were created by "Takashi Yamamoto" at Keio University
(looking at the HTML page), I am not sure if this is really correct, because he seems to be
an experimentalist (for organic synthesis). FYI, he is not the same person with me (please note
a slight difference in the first name "Takashi" vs "Takeshi" -- very confusing though!)

I've checked the above Wikibooks page again, but still cannot find the name of the person
who created it. (FYI, I myself have not contributed anything to those pages.)

So, unless the above person ("Takashi Yamamoto") is indeed the author of the Wikibook pages
(which seems unlikely to me), I guess it might be better to change the "contributor" item to 
something like "Japanese community", "Community efforts", or something like that...?
It may also be nice to directly link

https://ja.wikibooks.org/wiki/Chapel

rather than my post in the Discourse.

(Because I am not familiar with PR on Github (yet), I would appreciate it
if the list will be updated such that the credit should not go to me (at least) :)

Thanks very much for your management, and best regards,
Takeshi Yamamoto

**Comment by mstrout** [comment]
Thank you Takeshi for the detailed GitHub issue!  I do apologize for the name mixup.  I made the fix.

**Comment by ty1027** [comment]
Thanks very much! I really appreciate it :)
